### ISSUE TITLE
1. 기능명세, 계획

### ISSUE THREAD

**Issue by cstangga** [ssg-java3-240304/oop-EcommerceAdmin#1]
1. 관리자 권한 : 회원/상품/주문 을 관리자용 시스템 
## 🌈 Success criteria 

1. 회원관리
    1) 회원추가 (중복아이디 검증)
    2) 회원삭제
    3) 회원정보수정
    4) 회원조회 - (UUID -> userName 아이디같은 개념)

2. 상품관리
    1) 재고관리
    2) 상품목록관리

3. 주문관리
    1) 전체 주문조회
    2) 주문생성

## 👷To-do

- [ ] ALL : 필드 설정
- [ ] repository = 싱글톤 예정
- [ ] 회원관리 1. (필드 변경 Customer#uuid -> Customer#userName) 
- [ ] 회원관리 2. 중복아이디 검증
